branches:
  only:
    - "/^v.*$/"
notifications:
  email:
    on_success: change
    on_failure: always
  irc: chat.freenode.net#dedupe
language: python
sudo: false
services: docker
matrix:
  include:
    - env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
before_install:
  - if ! [[ $TRAVIS_TAG ]]; then exit 0; fi
install:
  - docker pull $DOCKER_IMAGE
script:
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/.manylinux-install.sh
after_success:
  - pip install twine && twine upload --skip-existing -u datamade.wheelbuilder -p $PYPIPASSWORD wheelhouse/*
  - exit 0
env:
  global:
    - secure: T3lCe9jJUbYLB0WHgSD+utrmJSvgcXCLi+Lwugsaa2SXIX8UzL7TbwHWB1t10H4sddy0QBBwanqRptv6iZ7gN0EtIE6+BDv6FJcNZJBDp13pUoQqq1Fm3OMbEniLrc/ubV6mZyJLHh6oNJtzSWPk1wrFvByLpYskeZIm4ayw4Mc=
