branches:
  only:
  - master
  - "/^v.*$/"
language: python
notifications:
  email:
    on_success: change
    on_failure: always
  irc: chat.freenode.net#dedupe
matrix:
  include:
  - os: linux
    python: 3.4
  - os: linux
    python: 2.7
  - os: osx
    language: generic
    env: BREW_PYTHON='python'
  - os: osx
    language: generic
    env: BREW_PYTHON='python3'
before_install:
- if [[ $BREW_PYTHON == 'python3' ]]; then brew update; brew install $BREW_PYTHON;
  python3 -m venv venv; source venv/bin/activate; fi
install:
- pip install --upgrade pip
- pip install wheel
- pip install numpy>=1.9.2
- pip install --upgrade -r requirements.txt
- pip install coveralls
- cython src/*.pyx
- pip install -e .
script:
- coverage run -m nose
- python tests/canonical.py -vv
after_success:
- coveralls
- echo [distutils]                                  > ~/.pypirc
- echo index-servers = pypi                        >> ~/.pypirc
- echo [pypi]                                      >> ~/.pypirc
- echo repository=https://pypi.python.org/pypi     >> ~/.pypirc
- echo username=datamade.wheelbuilder              >> ~/.pypirc
- echo password=$PYPIPASSWORD                      >> ~/.pypirc
- if [[ $TRAVIS_TAG && "$TRAVIS_OS_NAME" == "osx" ]]; then python setup.py bdist_wheel
  upload; fi
- if [[ $TRAVIS_TAG && "$TRAVIS_OS_NAME" == "linux" ]]; then python setup.py sdist
  upload; fi
env:
  global:
  - secure: ijl8Uh+YNLDV3w9hrz/B93fRMQaR2QtJfRc33gCnkj2V0rmlQQgzpmTq/RuTLzN+Lc0kEs11UishKYwuNXEGXyeM+EMG9SvOlYjXW5a0PB3ZuenzY7xctVM22pusb3cw520xigQ1zchgaqJa0jGcHENweqXZPDKnhbcYLLl+7Sw=
