# Continuous integration procedure for AppVeyor
# Based on https://raw.githubusercontent.com/choderalab/itctools/master/appveyor.yml

environment:

  matrix:
    - arch : 32
      python : 27
    - arch : 64
      python : 34

install:
  - "SET PATH=C:\\Python%PYTHON%;c:\\Python%PYTHON%\\scripts;%PATH%"
  - python -m pip install --upgrade pip
  - pip install numpy
  - pip install -r requirements.txt
  - cython src/cpredicates.pyx
  - pip install -e . 

build: false

test_script:
  # Nosetests take care of unit tests
  # Behave runs the example scripts and tries to verify if it produces the right output
  - coverage run -m nose
  - python tests/canonical.py

after_test:
  - pip install wheel
  - python setup.py bdist_wheel

artifacts:
  - path: dist\*

on_success:
  # Could run coveralls here but will leave that to travis tests
  - echo Build succesful!
  - coverage report
