# Continuous integration procedure for AppVeyor
# Based on https://raw.githubusercontent.com/choderalab/itctools/master/appveyor.yml

environment:
  password:
    secure: uOcv5TOm/CgwOmiLQhNX+g==

  matrix:
    - python : 27
    - python : 27-x64
    - python : 34
    - python : 34-x64

install:
  - "SET PATH=C:\\Python%PYTHON%;c:\\Python%PYTHON%\\scripts;%PATH%"
  - python -m pip install --upgrade pip
  - pip install numpy
  - pip install -r requirements.txt
  - cython src/cpredicates.pyx
  - pip install -e . 

build: false

test_script:
  # Nosetests take care of unit tests
  # Behave runs the example scripts and tries to verify if it produces the right output
  - coverage run -m nose
  - python tests/canonical.py

after_test:
  - pip install wheel
  - pip wheel --wheel-dir=wheelhouse .

artifacts:
  - path: wheelhouse\*

on_success:
  # Could run coveralls here but will leave that to travis tests
  - echo Build succesful!
  - coverage report

deploy_script:
  - echo [distutils]                                  > %USERPROFILE%\\.pypirc
  - echo index-servers =                             >> %USERPROFILE%\\.pypirc
  - echo     pypi                                    >> %USERPROFILE%\\.pypirc
  - echo [pypi]                                      >> %USERPROFILE%\\.pypirc
  - echo repository=https://pypi.python.org/pypi     >> %USERPROFILE%\\.pypirc
  - echo username=fgregg                             >> %USERPROFILE%\\.pypirc
  - echo password=%password%                         >> %USERPROFILE%\\.pypirc
  - set HOME=%USERPROFILE%
  - pip install wheel
  - if "%APPVEYOR_REPO_TAG%"=="true" ( python setup.py bdist_wheel upload )

deploy : on
